services:
  library-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - OTEL_SERVICE_NAME=library-api
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
  jaeger:
    image: jaegertracing/all-in-one:1.41
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686" # Jaeger UI
      - "4317:4317" # gRPC endpoint for OTLP

